name 'geth'
maintainer 'Nikita Sobolevsky'
maintainer_email 'meganuke@meganuke.ru'
license 'GPL-3.0'
description 'Installs/Configures Go Ethereum'
long_description 'Installs/Configures Go Ethereum'
supports 'ubuntu', '>= 18.0.4'
supports 'debian', '>= 8.0'
supports 'centos', '>= 7.0'
supports 'redhat', '>= 7.0'
version '1.0.0'
gem 'toml', '~> 0.2.0'
chef_version '>= 13.0'
depends 'tar', '~> 2.2.0'
issues_url 'https://github.com/nikitasobolevsky/chef-geth/issues'
source_url 'https://github.com/nikitasobolevsky/chef-geth'
